using System;
using System.Collections.Generic;
using System.Linq;
using Dfe.Edis.SourceAdapter.Sld.Domain.SubmitLearnerData;
using Microsoft.OData.Edm;

namespace Dfe.Edis.SourceAdapter.Sld.AcceptanceTests.Helpers
{
    public static class RandomDataGenerator
    {
        public static int Number(int min, int max)
        {
            return ThreadSafeRandom.Next(min, max);
        }

        public static string String(char[] validChars, int length)
        {
            var chars = new char[length];

            for (var i = 0; i < length; i++)
            {
                chars[i] = Entry(validChars);
            }

            return new string(chars);
        }

        public static string String(int length)
        {
            var validChars = new[]
            {
                'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'W', 'X', 'Y', 'Z',
                '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
            };
            return String(validChars, length);
        }

        public static DateTime DateInPast(int minYearsAgo, int maxYearsAgo)
        {
            var year = Number(DateTime.Today.Year - maxYearsAgo, DateTime.Today.Year - minYearsAgo);
            var month = Number(1, 12);
            var day = Number(1, 28);

            return new DateTime(year, month, day);
        }

        public static DateTime DateInFuture(int minYears, int maxYears)
        {
            var year = Number(DateTime.Today.Year + minYears, DateTime.Today.Year + maxYears);
            var month = Number(1, 12);
            var day = Number(1, 28);

            return new DateTime(year, month, day);
        }

        public static DateTime DateAfter(DateTime startDate, int minDays, int maxDays)
        {
            var days = Number(minDays, maxDays);
            return startDate.AddDays(days);
        }

        public static T Entry<T>(IEnumerable<T> items)
        {
            var count = items == null ? 0 : items.Count();
            if (count < 1)
            {
                return default;
            }

            var index = Number(0, count - 1);
            return items.ElementAt(index);
        }

        public static string FirstName(bool includeBoysNames = true, bool includeGirlsNames = true)
        {
            if (includeBoysNames && includeGirlsNames)
            {
                return Entry(AllFirstNames);
            }

            if (includeGirlsNames)
            {
                return Entry(GirlsNames);
            }

            if (includeBoysNames)
            {
                return Entry(BoysNames);
            }

            return null;
        }

        public static string LastName()
        {
            return Entry(Surnames);
        }

        public static string Nino()
        {
            var validPrefixChars = new[] {'A', 'B', 'C', 'E', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'W', 'X', 'Y', 'Z'};
            var validSuffixChars = new[] {'A', 'B', 'C', 'D'};

            var prefix1 = Entry(validPrefixChars);
            var prefix2 = Entry(validPrefixChars);
            var digit1 = Number(1, 9);
            var digit2 = Number(1, 9);
            var digit3 = Number(1, 9);
            var digit4 = Number(1, 9);
            var digit5 = Number(1, 9);
            var digit6 = Number(1, 9);
            var suffix = Entry(validSuffixChars);

            return $"{prefix1}{prefix2}{digit1}{digit2}{digit3}{digit4}{digit5}{digit6}{suffix}";
        }

        public static Learner Learner(int ukprn)
        {
            var learnRefNoChars = new[]
            {
                'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'W', 'X', 'Y', 'Z',
                '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
            };

            var learningDeliveries = Enumerable.Range(1, Number(2, 5)).Select(index =>
            {
                var learnPlanEndDate = DateInFuture(0, 2);
                var learnActEndDate = DateAfter(learnPlanEndDate, 0, 180);
                return new LearningDelivery
                {
                    AimType = Number(25, 45),
                    LearnStartDate = DateInPast(1, 3),
                    LearnPlanEndDate = learnPlanEndDate,
                    FundModel = Number(30, 35),
                    StdCode = Number(10, 50),
                    DelLocPostCode = null,
                    EpaOrgId = String(5),
                    CompStatus = Number(1, 6),
                    LearnActEndDate = learnActEndDate,
                    WithdrawReason = Number(0, 4),
                    Outcome = Number(1, 9),
                    AchDate = DateAfter(learnActEndDate, 10, 30),
                    OutGrade = String(1),
                    ProgType = Number(30, 39),
                };
            }).ToArray();

            return new Learner
            {
                Ukprn = ukprn,
                LearnRefNumber = String(learnRefNoChars, 8),
                Uln = Number(100000000, 999999999),
                GivenNames = FirstName(),
                FamilyName = LastName(),
                NiNumber = Nino(),
                DateOfBirth = DateInPast(16, 30),
                LearningDeliveries = learningDeliveries,
            };
        }


        // Given names taken from https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/babynamesenglandandwales/2019#top-100-baby-names
        private static readonly string[] BoysNames = new[]
        {
            "Aaron",
            "Abdul",
            "Adam",
            "Adrian",
            "Aidan",
            "Aiden",
            "Alan",
            "Albert",
            "Albie",
            "Alec",
            "Alex",
            "Alexander",
            "Alfie",
            "Alfred",
            "Allan",
            "Andrew",
            "Anthony",
            "Antony",
            "Archibald",
            "Archie",
            "Arlo",
            "Arnold",
            "Arthur",
            "Ashley",
            "Ashton",
            "Austin",
            "Bailey",
            "Barrie",
            "Barry",
            "Basil",
            "Ben",
            "Benjamin",
            "Bernard",
            "Bertie",
            "Bertram",
            "Billy",
            "Blake",
            "Bobby",
            "Bradley",
            "Brandon",
            "Brett",
            "Brian",
            "Bruce",
            "Bryan",
            "Caleb",
            "Callum",
            "Calum",
            "Cameron",
            "Carl",
            "Carter",
            "Cecil",
            "Charles",
            "Charlie",
            "Chester",
            "Christian",
            "Christopher",
            "Clarence",
            "Claude",
            "Clifford",
            "Clive",
            "Colin",
            "Connor",
            "Conor",
            "Corey",
            "Craig",
            "Curtis",
            "Cyril",
            "Dale",
            "Damian",
            "Damien",
            "Daniel",
            "Danny",
            "Darren",
            "David",
            "Dean",
            "Declan",
            "Denis",
            "Dennis",
            "Derek",
            "Derrick",
            "Desmond",
            "Dexter",
            "Dominic",
            "Donald",
            "Douglas",
            "Duncan",
            "Dylan",
            "Edgar",
            "Edmund",
            "Edward",
            "Edwin",
            "Elijah",
            "Elliot",
            "Elliott",
            "Ellis",
            "Eric",
            "Ernest",
            "Ethan",
            "Evan",
            "Ewan",
            "Ezra",
            "Felix",
            "Finlay",
            "Finley",
            "Finn",
            "Francis",
            "Frank",
            "Frankie",
            "Fred",
            "Freddie",
            "Frederick",
            "Gabriel",
            "Gareth",
            "Garry",
            "Gary",
            "Gavin",
            "Geoffrey",
            "George",
            "Gerald",
            "Gerard",
            "Gilbert",
            "Glen",
            "Glenn",
            "Gordon",
            "Graeme",
            "Graham",
            "Grayson",
            "Gregory",
            "Guy",
            "Harley",
            "Harold",
            "Harrison",
            "Harry",
            "Harvey",
            "Hayden",
            "Hector",
            "Henry",
            "Herbert",
            "Horace",
            "Howard",
            "Hubert",
            "Hudson",
            "Hugh",
            "Hugo",
            "Hunter",
            "Iain",
            "Ian",
            "Ibrahim",
            "Isaac",
            "Ivan",
            "Ivor",
            "Jack",
            "Jackson",
            "Jacob",
            "Jake",
            "James",
            "Jamie",
            "Jason",
            "Jasper",
            "Jaxon",
            "Jay",
            "Jayden",
            "Jeffrey",
            "Jenson",
            "Jeremy",
            "Jesse",
            "Joe",
            "Joel",
            "Joey",
            "John",
            "Jonathan",
            "Jordan",
            "Joseph",
            "Josh",
            "Joshua",
            "Jude",
            "Julian",
            "Justin",
            "Kai",
            "Kane",
            "Karl",
            "Kayden",
            "Keith",
            "Kenneth",
            "Kevin",
            "Kian",
            "Kieran",
            "Kieron",
            "Kyle",
            "Laurence",
            "Lawrence",
            "Lee",
            "Leigh",
            "Leo",
            "Leon",
            "Leonard",
            "Leslie",
            "Lewis",
            "Liam",
            "Lionel",
            "Logan",
            "Louie",
            "Louis",
            "Luca",
            "Lucas",
            "Luke",
            "Macauley",
            "Malcolm",
            "Marc",
            "Marcus",
            "Mark",
            "Martin",
            "Martyn",
            "Mason",
            "Mathew",
            "Matthew",
            "Maurice",
            "Max",
            "Melvyn",
            "Michael",
            "Mitchell",
            "Mohamed",
            "Mohammad",
            "Mohammed",
            "Morgan",
            "Morris",
            "Muhammad",
            "Nathan",
            "Neil",
            "Neville",
            "Nicholas",
            "Nigel",
            "Noah",
            "Noel",
            "Norman",
            "Oakley",
            "Oliver",
            "Ollie",
            "Oscar",
            "Owen",
            "Patrick",
            "Paul",
            "Percival",
            "Percy",
            "Peter",
            "Philip",
            "Phillip",
            "Ralph",
            "Raymond",
            "Reece",
            "Reggie",
            "Reginald",
            "Reuben",
            "Rhys",
            "Richard",
            "Ricky",
            "Riley",
            "Robert",
            "Robin",
            "Rodney",
            "Roger",
            "Roland",
            "Roman",
            "Ronald",
            "Ronnie",
            "Rory",
            "Ross",
            "Rowan",
            "Roy",
            "Royston",
            "Russell",
            "Ryan",
            "Sam",
            "Samuel",
            "Scott",
            "Sean",
            "Sebastian",
            "Seth",
            "Shane",
            "Shaun",
            "Sidney",
            "Simon",
            "Sonny",
            "Spencer",
            "Stanley",
            "Stephen",
            "Steven",
            "Stewart",
            "Stuart",
            "Sydney",
            "Taylor",
            "Teddy",
            "Terence",
            "Terry",
            "Theo",
            "Theodore",
            "Thomas",
            "Timothy",
            "Tobias",
            "Toby",
            "Tom",
            "Tommy",
            "Tony",
            "Trevor",
            "Tyler",
            "Victor",
            "Vincent",
            "Walter",
            "Wayne",
            "Wilfred",
            "William",
            "Zachary",
            "Zak",
        };

        private static readonly string[] GirlsNames = new[]
        {
            "Aaliyah",
            "Abbie",
            "Abby",
            "Abigail",
            "Ada",
            "Agnes",
            "Aimee",
            "Aisha",
            "Alexandra",
            "Alice",
            "Alicia",
            "Alisha",
            "Alison",
            "Alma",
            "Amanda",
            "Amber",
            "Amelia",
            "Amelie",
            "Amy",
            "Andrea",
            "Angela",
            "Anita",
            "Ann",
            "Anna",
            "Annabelle",
            "Anne",
            "Annette",
            "Annie",
            "Arabella",
            "Aria",
            "Ashleigh",
            "Audrey",
            "Aurora",
            "Ava",
            "Ayla",
            "Barbara",
            "Beatrice",
            "Bella",
            "Bertha",
            "Beryl",
            "Bessie",
            "Beth",
            "Bethan",
            "Bethany",
            "Betty",
            "Beverley",
            "Blanche",
            "Bonnie",
            "Brenda",
            "Bridget",
            "Brooke",
            "Caitlin",
            "Carla",
            "Carly",
            "Carol",
            "Carole",
            "Caroline",
            "Carolyn",
            "Catherine",
            "Cerys",
            "Chantelle",
            "Charlene",
            "Charlie",
            "Charlotte",
            "Chelsea",
            "Cheryl",
            "Chloe",
            "Christina",
            "Christine",
            "Clair",
            "Claire",
            "Clara",
            "Clare",
            "Constance",
            "Courtney",
            "Cynthia",
            "Daisy",
            "Danielle",
            "Daphne",
            "Darcey",
            "Darcie",
            "Darcy",
            "Dawn",
            "Debbie",
            "Deborah",
            "Debra",
            "Delilah",
            "Demi",
            "Denise",
            "Diana",
            "Diane",
            "Donna",
            "Dora",
            "Doreen",
            "Doris",
            "Dorothy",
            "Edith",
            "Edna",
            "Eileen",
            "Elaine",
            "Eleanor",
            "Elise",
            "Eliza",
            "Elizabeth",
            "Ella",
            "Elle",
            "Ellen",
            "Ellie",
            "Eloise",
            "Elsie",
            "Emilia",
            "Emily",
            "Emma",
            "Enid",
            "Erin",
            "Esme",
            "Esther",
            "Ethel",
            "Eva",
            "Eve",
            "Evelyn",
            "Evie",
            "Faith",
            "Fanny",
            "Felicity",
            "Fiona",
            "Florence",
            "Frances",
            "Francesca",
            "Freda",
            "Freya",
            "Gabrielle",
            "Gail",
            "Gemma",
            "Georgia",
            "Georgina",
            "Geraldine",
            "Gertrude",
            "Gillian",
            "Gladys",
            "Glenys",
            "Gloria",
            "Glynis",
            "Grace",
            "Gracie",
            "Gwendoline",
            "Hallie",
            "Hannah",
            "Harper",
            "Harriet",
            "Hayley",
            "Hazel",
            "Heather",
            "Heidi",
            "Helen",
            "Hilary",
            "Hilda",
            "Hollie",
            "Holly",
            "Ida",
            "Imogen",
            "Irene",
            "Iris",
            "Isabel",
            "Isabella",
            "Isabelle",
            "Isla",
            "Isobel",
            "Ivy",
            "Jacqueline",
            "Jade",
            "Jane",
            "Janet",
            "Janice",
            "Jasmine",
            "Jayne",
            "Jean",
            "Jeanette",
            "Jemma",
            "Jenna",
            "Jennifer",
            "Jenny",
            "Jessica",
            "Jessie",
            "Jill",
            "Joan",
            "Joanna",
            "Joanne",
            "Jodie",
            "Jordan",
            "Josephine",
            "Joy",
            "Joyce",
            "Judith",
            "Julia",
            "Julie",
            "June",
            "Karen",
            "Kate",
            "Katherine",
            "Kathleen",
            "Kathryn",
            "Katie",
            "Katy",
            "Kay",
            "Kayla",
            "Kayleigh",
            "Keira",
            "Kelly",
            "Kelsey",
            "Kerry",
            "Kiera",
            "Kim",
            "Kimberley",
            "Kirsty",
            "Lacey",
            "Laila",
            "Lara",
            "Laura",
            "Lauren",
            "Layla",
            "Leah",
            "Leanne",
            "Lesley",
            "Lexi",
            "Lexie",
            "Libby",
            "Lilian",
            "Lillian",
            "Lilly",
            "Lily",
            "Linda",
            "Lindsay",
            "Lindsey",
            "Lisa",
            "Lola",
            "Lorraine",
            "Lottie",
            "Louisa",
            "Louise",
            "Lucy",
            "Luna",
            "Lydia",
            "Lyla",
            "Lynda",
            "Lyndsey",
            "Lynn",
            "Lynne",
            "Lynsey",
            "Mabel",
            "Maddison",
            "Madeleine",
            "Madison",
            "Maisie",
            "Maisy",
            "Mandy",
            "Margaret",
            "Margery",
            "Margot",
            "Maria",
            "Marian",
            "Marie",
            "Marilyn",
            "Marina",
            "Marion",
            "Marjorie",
            "Marlene",
            "Martha",
            "Mary",
            "Maryam",
            "Matilda",
            "Maud",
            "Maureen",
            "Mavis",
            "Maxine",
            "May",
            "Maya",
            "Megan",
            "Melanie",
            "Melissa",
            "Mia",
            "Michele",
            "Michelle",
            "Mila",
            "Mildred",
            "Millicent",
            "Millie",
            "Minnie",
            "Miriam",
            "Mollie",
            "Molly",
            "Monica",
            "Morgan",
            "Muriel",
            "Mya",
            "Nancy",
            "Naomi",
            "Natalie",
            "Natasha",
            "Nellie",
            "Niamh",
            "Nichola",
            "Nicola",
            "Nicole",
            "Nora",
            "Norah",
            "Norma",
            "Olive",
            "Olivia",
            "Orla",
            "Paige",
            "Pamela",
            "Patricia",
            "Paula",
            "Pauline",
            "Peggy",
            "Penelope",
            "Phoebe",
            "Phyllis",
            "Poppy",
            "Rachael",
            "Rachel",
            "Rebecca",
            "Rebekah",
            "Rhiannon",
            "Rita",
            "Robyn",
            "Rose",
            "Rosemary",
            "Rosie",
            "Rosina",
            "Ruby",
            "Ruth",
            "Sally",
            "Samantha",
            "Sandra",
            "Sara",
            "Sarah",
            "Scarlett",
            "Shannon",
            "Sharon",
            "Sheila",
            "Shirley",
            "Sian",
            "Sienna",
            "Skye",
            "Sofia",
            "Sonia",
            "Sophia",
            "Sophie",
            "Stacey",
            "Stella",
            "Stephanie",
            "Summer",
            "Susan",
            "Suzanne",
            "Sybil",
            "Sylvia",
            "Tanya",
            "Tara",
            "Tegan",
            "Teresa",
            "Thea",
            "Thelma",
            "Theresa",
            "Tia",
            "Tilly",
            "Tina",
            "Toni",
            "Tracey",
            "Tracy",
            "Valerie",
            "Vanessa",
            "Vera",
            "Veronica",
            "Victoria",
            "Violet",
            "Vivienne",
            "Wendy",
            "Willow",
            "Winifred",
            "Yasmin",
            "Yvonne",
            "Zara",
            "Zoe",
        };

        private static readonly string[] AllFirstNames = BoysNames.Concat(GirlsNames).ToArray();

        // Surnames taken from https://en.wikipedia.org/wiki/List_of_most_common_surnames_in_Europe#United_Kingdom
        private static readonly string[] Surnames = new[]
        {
            "Anderson",
            "Brown",
            "Campbell",
            "Clark",
            "Davies",
            "Doherty",
            "Driscoll",
            "Edwards",
            "Evans",
            "Graham",
            "Green",
            "Griffiths",
            "Hall",
            "Hamilton",
            "Hughes",
            "Jackson",
            "James",
            "Jenkins",
            "Johnson",
            "Johnston",
            "Jones",
            "Kelly",
            "Lewis",
            "MacDonald",
            "Martin",
            "McLaughlin",
            "Mitchell",
            "Moore",
            "Morgan",
            "Morrison",
            "Moss",
            "Murphy",
            "Murray",
            "O’Neill",
            "Owen",
            "Paterson",
            "Phillips",
            "Price",
            "Quinn",
            "Rees",
            "Reid",
            "Roberts",
            "Robertson",
            "Robinson",
            "Ross",
            "Scott",
            "Smith",
            "Smyth",
            "Stewart",
            "Taylor",
            "Thomas",
            "Thompson",
            "Thomson",
            "Walker",
            "Watson",
            "White",
            "Williams",
            "Wilson",
            "Wood",
            "Wright",
            "Young",
        };
    }
}